### ISSUE TITLE
#spy/d stopped working in 1.9?

### ISSUE THREAD

**Issue by mattiasw2** [dgrnbrg/spyscope#26]
(take 20 (repeat #spy/d (+ 1 2 3)))

gives

         ClassCastException java.io.StringWriter cannot be cast to clojure.lang.Associative  clojure.lang.RT.assoc (RT.java:807)

in clojure 1.9

**Comment by saulshanabrook** [comment]
Maybe this was fixed in https://github.com/dgrnbrg/spyscope/pull/23? If so, could you do a release with this change in it?

**Comment by schmee** [comment]
@saulshanabrook I don't think that's the same issue. 1.5 doesn't even load in Clojure 1.9 due to the new spec-ed core macros, but 1.6 works and is already on Clojars. That said, I just ran into this as well.

**Comment by mattiasw2** [comment]
Are you saying that 1.6 works with clojure 1.9? For me, only #spy/p works. For #spy/t and #spy/d, I get the ClassCastException.

So, I am waiting for a 1.7. (I really wished I know a simple way to make lein use the latest spycore from github.)

**Comment by schmee** [comment]
I'm saying that before 1.6, Spyscope didn't even load in Clojure 1.9. If I understand thing correctly, this issue (about `#spy/d` not working) is not solved by #23, and the bug is is still present in master.

**Comment by schmee** [comment]
This has been fixed by https://github.com/dgrnbrg/spyscope/pull/25. The new version is not up on Clojars however, so to make it work, clone this repo and run `lein install` on the master branch and update your code to use `[spyscope "0.1.7-SNAPSHOT"]`.

**Comment by seancorfield** [comment]
Someone just asked about spyscope in #clojure on the Clojurians Slack. The README still shows 0.1.5 as the current version(!) and they're on Clojure 1.9 so they didn't know about 0.1.6 including the fix for the bad `ns` forms.

Since there's a blocking bug in 0.1.6 with a fix already in master, it would be nice if @dgrnbrg could cut a 0.1.7 release with that fix and update the README to show that as the latest version.

**Comment by waffletower** [comment]
I would just make a pull request for the readme.  Since Clojure 1.9 now has an RC1 build, we might be able to persuade @dgrnbrg to push a jar to clojars.

**Comment by expez** [comment]
Clojure 1.9 is out now.  Would be lovely to get a new jar.

**Comment by waffletower** [comment]
Maybe he could be convinced to release 1.7 after approving the clojurescript PR.

**Comment by emil0r** [comment]
Any news on this? Bit annoying to have a SNAPSHOT locally installed. Love the library, but please release a new version to Clojars!

**Comment by randomizedthinking** [comment]
Any update on the fix for Clojure 1.9, or maybe even Clojure 1.10?

**Comment by dgrnbrg** [comment]
I’d be happy to add another contributor to manage new releases!

**Comment by randomizedthinking** [comment]
I am a Clojure new comer. Yet, if someone would like to help me out, I'd like to take the role to manage the new releases.

**Comment by expez** [comment]
@slipset Is this something [clj-commons](https://github.com/clj-commons) might be interested in adopting?  That way @randomizedthinking has someone to help him with maintainership logistics?

Does that sound interesting to you too, @dgrnbrg?  

You can read more about clj-commons [here](https://clojureverse.org/t/what-is-clj-commons/3162) but in short it's an org set up to let finished / unmaintained projects sunset gracefully.

**Comment by buzzdan** [comment]
Any updates on this issue?

**Comment by mk12** [comment]
Looks like someone else has [published 0.1.7 on clojars](https://clojars.org/spieden/spyscope). I'm using that for now -- `#spy/d` seems to be working on Clojure 1.10.

**Comment by rbeesley** [comment]
> Looks like someone else has [published 0.1.7 on clojars](https://clojars.org/spieden/spyscope). I'm using that for now -- `#spy/d` seems to be working on Clojure 1.10.

On Clojure 1.8.0 -> 1.10.2, I can't get _this_ version to load. Not sure what's going on. I tried to add the dependencies in `project.clj` based on the documentation for the 1.6 version with changes to match the 1.7 version referenced here:

```
:dependencies [[spieden/spyscope "0.1.7"]]
:injections [(require 'spyscope.core)]
```

However I get this error when starting my REPL:

```
user.core=> (require 'spyscope.core)
Syntax error (IllegalArgumentException) compiling deftype* at (clojure\core\rrb_vector\rrbt.clj:282:1).
Must hint overloaded method: toArray
```

This seems to be coming from when I require the namespace because it won't happen immediately until I `use` or `require` spyscope.core.

Edit: Looks like it might be because I have Java 15.0.1 running.

Edit 2: Seemed to resolve things using the `:managed-dependency` suggestion from issue https://github.com/dgrnbrg/spyscope/issues/32#issuecomment-562356811, and the above 0.1.7 version of this library.

Edit 3: For completeness, if anyone else hits this, I used the following in my `project.clj`:
```
:profiles {:skyscope {:dependencies [[spieden/spyscope "0.1.7"]]
                      ;; Force Spyscope to use a newer version of rrb-vector that is compatible with Java 11
                      :managed-dependencies [[org.clojure/core.rrb-vector "0.1.2"]]
                      :injections [(require 'spyscope.core)]}
```

This was working with Clojure 1.10.2 on AdoptOpenJDK (build 15.0.1+9).

**Comment by waffletower** [comment]
I believe updating the fipp dependency repairs this.

I have a fork of 0.1.7 here:
https://github.com/waffletower/spyscope

**Comment by slipset** [comment]
I've released clj-commons/spyscope here https://clojars.org/clj-commons/spyscope
Updated all libs to most recent.

**Comment by rbeesley** [comment]
@slipset, seems to be working with the clj-commons release with no additional dependencies.
